disabled_rules:
  - trailing_whitespace
  - line_length
  - orphaned_doc_comment

opt_in_rules:
  - let_var_whitespace

included:
  - Havit
excluded:
  # AppDelegate, SceneDelegate file 무시
  - Havit-iOS/Havit/Havit/Global/Supports/AppDelegate.swift
  - Havit-iOS/Havit/Havit/Global/Supports/SceneDelegate.swift

identifier_name:
  excluded:
    - id

force_cast: warning

identifier_name:
  min_length:
    warning: 1 # only warning
